#!/bin.perl

$title = shift;
$title = "repository generated by eurocontrol's synergy2git" if (!$title);
$ccm_cmd = shift;
$ccm_cmd = "ccm" if (!$ccm_cmd);

while(<STDIN>) {
  chomp;
  next if (/\*+/);
  if (/^Object:\s*(\S+) \(project:([^)]*)\)/) {
    $object = $1;
    $objects{$object}{"project"} = $2;
  }elsif(/^(Owner|Created|Task): *(\S.+)/) {
    $objects{$object}{$1} = $2;
  }elsif(/^(Comment|Predecessors|Successors):\s*(\S.*|)$/){
    $typename = $1;
    push(@{$objects{$object}{$typename}}, $2) if ($2) ;
  }else{
    s/^\s*//;
    push(@{$objects{$object}{$typename}}, $_) if ($_);
  }
}

foreach $k (keys %objects) {
  if ($#{$objects{$k}{"Predecessors"}} < 0) {
    push (@firsts, $k);
  }
}

sub key2tagname {
  my ($key) = @_;
  $key =~ s/[#:]/_/g;
  return $key;
}

sub followtree {
  my ($key, $tirets) = @_;
  my $cauthor, $cdate, $ccomment, $cpredecessor, $cbranch;
  $cbranch = key2tagname($key);
  $cpredecessor = key2tagname($objects{$key}{"Predecessors"}[0]);
  $cpredecessor = "initial_commit" unless($cpredecessor);
  $owner = $objects{$key}{"Owner"};
  $cauthor = "$owner <" . $owner . "\@eurocontrol.int>";
  $cdate = $objects{$key}{"Created"};
  $ccommit = join(" ", @{$objects{$key}{"Comment"}});
  print "git checkout tags/$cpredecessor\n";
  print "git branch $cbranch\n";
  print "git checkout branches/$cbranch\n";
  print "rm -rf *;\n";
  print "$ccm_cmd cfs \"$key\" -p .\n";
  print "git add -A *\n";
  print "git commit --author \"$cauthor\" --date \"$cdate\" -m \"$ccomment (imported via git2synergy)\"\n";
  print "git tag $cbranch\n";
  print STDERR "$tirets $key\n";
  foreach $successor (@{$objects{$key}{"Successors"}}) {
    followtree($successor, $tirets.'-');
  }
}
print("mkdir repo\n");
print("cd repo\n");
print("rm -rf .git *\n");
print("git init\n");
print("printf \"# $title \\n\\nrepository generated automaticaly\\n\" > README.md\n");
print("git add README.md\n");
print("git commit --author=\"synergy2git <contact@24eme.fr>\" -m \"initial commit\"\n");
print("git tag initial_commit\n");
foreach $first (@firsts) {
  followtree($first, '-');
}
print ("git-big-picture -o ../repo.png -a .\n");
print ("cd ..\n");
